# backend/app/services/keyword_map.py

# ─────────────────────────────────────────
# 웹 검색어 키워드 매핑 테이블
# 새로운 도메인 추가 시 여기서만 수정
# ─────────────────────────────────────────

KEYWORD_MAP: dict[str, str] = {

    # ── 문서 / 보고서 ──────────────────────
    "중간 계획서":    "mid-term project plan writing guide",
    "중간계획서":     "mid-term project plan writing guide",
    "최종 보고서":    "final project report writing guide",
    "최종보고서":     "final project report writing guide",
    "계획서":         "project plan document writing guide",
    "보고서":         "project report writing guide",
    "제안서":         "project proposal writing guide",
    "명세서":         "project specification document guide",
    "요구사항":       "software requirements specification guide",

    # ── 정보보호 / 보안 ────────────────────
    "정보보호":       "information security basics tutorial",
    "보안":           "information security tutorial",
    "암호화":         "encryption algorithm tutorial",
    "해킹":           "ethical hacking basics tutorial",
    "방화벽":         "firewall configuration tutorial",
    "취약점":         "vulnerability analysis security tutorial",
    "인증":           "authentication security tutorial",
    "접근제어":       "access control security tutorial",

    # ── 리눅스 명령어 ──────────────────────
    "파일 권한":      "linux file permissions tutorial",
    "파일권한":       "linux file permissions tutorial",
    "프로세스":       "linux process management tutorial",
    "쉘스크립트":     "linux shell script examples",
    "쉘":            "linux shell scripting tutorial",
    "배시":          "bash shell scripting tutorial",
    "crontab":       "linux crontab tutorial",
    "cron":          "linux cron job tutorial",
    "chmod":         "linux chmod command",
    "chown":         "linux chown command",
    "grep":          "linux grep command",
    "find":          "linux find command",
    "vim":           "linux vim editor commands",
    "nano":          "linux nano editor",
    "bash":          "bash scripting tutorial",
    "unix":          "unix operating system overview",
    "linux":         "linux basics tutorial",
    "ifconfig":      "linux ifconfig network command",
    "netstat":       "linux netstat command",
    "sudo":          "linux sudo command usage",
    "curl":          "linux curl command usage",
    "wget":          "linux wget command usage",
    "tar":           "linux tar command",
    "ssh":           "linux ssh command tutorial",
    "apt":           "linux apt package manager",
    "yum":           "linux yum package manager",
    "ping":          "linux ping command network",
    "kill":          "linux kill command process",
    "mkdir":         "linux mkdir command",
    "ls":            "linux ls command",
    "cd":            "linux cd command",
    "rm":            "linux rm command",
    "cp":            "linux cp command",
    "mv":            "linux mv command",
    "cat":           "linux cat command",
    "vi":            "linux vi editor commands",
    "ps":            "linux ps command process",
    "top":           "linux top command monitor",
    "df":            "linux df disk usage command",
    "du":            "linux du command usage",

    # ── Python / 개발 ──────────────────────
    "sqlalchemy":    "sqlalchemy python tutorial",
    "pydantic":      "pydantic python tutorial",
    "fastapi":       "fastapi official docs tutorial",
    "asyncio":       "python asyncio tutorial",
    "django":        "django python tutorial",
    "flask":         "flask python tutorial",
    "파이썬":         "python official docs tutorial",
    "python":        "python official docs tutorial",

    # ── AI / RAG ───────────────────────────
    "chromadb":      "chromadb vector store python tutorial",
    "langchain":     "langchain python tutorial",
    "openai":        "openai api python tutorial",
    "ollama":        "ollama local llm tutorial",
    "gemma":         "gemma model tutorial",
    "임베딩":         "text embedding tutorial python",
    "벡터":           "vector database tutorial python",
    "rag":           "retrieval augmented generation tutorial",
    "llm":           "large language model tutorial",

    # ── DevOps / 인프라 ────────────────────
    "docker compose": "docker compose tutorial",
    "kubernetes":    "kubernetes tutorial",
    "docker":        "docker official docs tutorial",
    "도커":           "docker official docs tutorial",
    "k8s":           "kubernetes k8s tutorial",
    "github":        "github tutorial",
    "git":           "git commands tutorial",
    "nginx":         "nginx configuration tutorial",
    "apache":        "apache web server tutorial",

    # ── 데이터베이스 ───────────────────────
    "postgresql":    "postgresql tutorial docs",
    "mongodb":       "mongodb tutorial docs",
    "sqlite":        "sqlite tutorial python",
    "mysql":         "mysql tutorial docs",
    "redis":         "redis tutorial docs",

    # ── 프론트엔드 ─────────────────────────
    "javascript":    "javascript tutorial mdn",
    "typescript":    "typescript tutorial docs",
    "리액트":         "react official docs tutorial",
    "react":         "react official docs tutorial",
    "html":          "html tutorial mdn",
    "css":           "css tutorial mdn",
    "TCP/IP":    "tcp ip networking tutorial",

    "OSI":       "osi model networking tutorial",
    "라우팅":    "network routing tutorial",


        # ── 운영체제 / 커널 ─────────────────────
    "입출력 관리":    "operating system IO management tutorial",
    "입출력":         "operating system input output management",
    "인터럽트":       "os interrupt handling tutorial",
    "인터럽트 처리":  "interrupt service routine tutorial",
    "버퍼 캐시":      "os buffer cache tutorial",
    "블록 장치":      "linux block device driver tutorial",
    "문자 장치":      "linux character device driver tutorial",
    "device driver":  "linux device driver tutorial",
    "디바이스 드라이버": "linux device driver tutorial",
    "파일 시스템":    "linux file system tutorial",
    "파일시스템":     "linux file system tutorial",
    "inode":         "linux inode file system tutorial",
    "vnode":         "linux vnode virtual file system tutorial",
    "vfs":           "linux virtual file system VFS tutorial",
    "스케줄링":       "operating system process scheduling tutorial",
    "cpu 스케줄링":   "cpu scheduling algorithms tutorial",
    "메모리 관리":    "operating system memory management tutorial",
    "가상 메모리":    "virtual memory os tutorial",
    "페이징":         "os paging memory management tutorial",
    "세그멘테이션":   "os segmentation memory tutorial",
    "프로세스 관리":  "os process management tutorial",
    "커널":           "unix linux kernel architecture tutorial",
    "시스템 콜":      "unix system call tutorial",
    "system call":    "unix linux system call tutorial",
    "fork":          "unix fork system call tutorial",
    "exec":          "unix exec system call tutorial",
    "pipe":          "unix pipe IPC tutorial",
    "signal":        "unix signal handling tutorial",
    "ipc":           "inter process communication IPC tutorial",
    "zombie":        "unix zombie process tutorial",
    "context switch": "os context switching tutorial",
    "컨텍스트 스위치": "os context switching tutorial",
}